name: CI

# This workflow should only be executed when version tag is pushed.
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      publish:
        description: Push to Docker Hub
        default: false

# There is one job in this workflow, to build and publish the image.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env

      - uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:qemu-v6.2.0
          platforms: all

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set run date
        run: echo "BUILD_DATE_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Docker build and push
        uses: docker/build-push-action@v2
        if: ${{ ! contains( env.XP_VERSION, '-SNAPSHOT') }}
        with:
          context: .
          pull: true
          no-cache: true
          push: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.publish == 'true' }}
          tags: ${{ env.IMAGE_FULL_TAG }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            build_date=${{ env.BUILD_DATE_TIME }}
            build_base_image=${{ env.BASE_IMAGE }}
            build_distro_version=${{ env.XP_VERSION }}
            build_jattach_version=${{ env.JATTACH_VERSION }}
