name: CI

# This workflow should only be executed when version tag is pushed.
on:
  push:
    tags:
      - 'v*'

# There is one job in this workflow, to build and publish the image.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env

      - uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:qemu-v6.1.0-20
          platforms: all

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set run date
        run: echo "BUILD_DATE_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Docker build and push
        uses: docker/build-push-action@v2
        if: ${{ ! contains( env.XP_VERSION, '-SNAPSHOT') }}
        with:
          context: .
          pull: true
          no-cache: true
          push: true
          tags: ${{ env.IMAGE_FULL_TAG }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7
          build-args: |
            build_date=${{ env.BUILD_DATE_TIME }}
            build_base_image=${{ env.BASE_IMAGE }}
            build_distro_version=${{ env.XP_VERSION }}