name: Nightly

# This workflow should only be executed when version tag is pushed.
on:
  schedule:
    - cron: '5 4 * * *'
  workflow_dispatch:
    inputs:
      publish:
        description: Push to Docker Hub Repository
        default: 'enonic/xp-experimental'

# There is one job in this workflow, to build and publish the image.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env

      - uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v6.2.0
          platforms: all

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Distro Path
        run: |
          XP_VERSION="${{ env.XP_VERSION }}"
          BASE_URL="https://repo.enonic.com/repository/snapshot/com/enonic/xp/enonic-xp-generic/$XP_VERSION"

          METADATA=$(curl -s "$BASE_URL/maven-metadata.xml")
          VALUE=$(echo "$METADATA" | grep -oPm1 "(?<=<value>)[^<]+")
          ARTIFACT_ID=$(echo "$METADATA" | grep -oPm1 "(?<=<artifactId>)[^<]+")

          echo "XP_DISTRO_PATH=$BASE_URL/$ARTIFACT_ID-$VALUE.tgz" >> $GITHUB_ENV

      - name: Set run date
        run: echo "BUILD_DATE_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          pull: true
          no-cache: true
          push: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.publish != '' }}
          tags: ${{ github.event.inputs.publish != '' && github.event.inputs.publish || 'enonic/xp' }}:nightly
          platforms: linux/amd64,linux/arm64
          build-args: |
            build_date=${{ env.BUILD_DATE_TIME }}
            build_base_image=${{ env.BASE_IMAGE }}
            build_distro_version=${{ env.XP_VERSION }}
            build_distro_path=${{ env.XP_DISTRO_PATH }}
